//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int Id { get; set; }
        public int PropertyId { get; set; }
        public int CustomerId { get; set; }
        public int RealtorId { get; set; }
        public System.DateTime Date { get; set; }
        public string RegistrationCode { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Property Property { get; set; }
        public virtual Realtor Realtor { get; set; }
    }
}
